# Escape Sequences
# Escape sequences are used to include special characters in strings.
# Common escape sequences:
# \n: Newline
# \t: Tab
# \\: Backslash
# \": Double quote
# \': Single quotes
print("Hello\nWorld!")
print("This is a tab\tcharacter.")
print("dogs are pet animals \ntigers are forest animals")
print("money is very impotant \" and it matters very much\"") 
print("dogs are pet animals \\ tigers are forest animals")
print("dogs are pet animals \' tigers are forest animals")
print("dogs are pet animals \t tigers are forest animals")