# print("hello,world! Welcome to python.")
# print("twinkel, twinkel, little star,\nhow i wonder what you are!")
# a = "sai"
# c = 20
# d = 6.5
# is_student = True

# print ("NAME   " + a +"  his age is   "+ str(c) +"  his height is  "+ str(d) 
#        +"  she is the student  "+ str(is_student ))
# num = "3000"
# a=int(num)
# b = int (num)+ 10
# print( int(num))
# print( int(num)+ 10)
# print(a)
# print(b)
# print ( " what is your favourite food")
# a = input( "my favourite is "  )
# print ("wow! i also like " + a )
# a = int(input())
# b = int(input())

# sum = int(a + b)
# difference =int( a-b)
# product =int( a* b)
# quotient = int(a/b)
# print ( sum)
# print(difference)
# print(product)
# print(quotient)
# print("hello \" python \" world! \n this is on a new line. \n this is a tab \t  after tab.")
a = int(input( " num 1\n" ))
b =int ( input ( "num 2\n"))
print("a is",a)
print("b is",b)
print(" square of a is", a**2)
print("square of b is " , b**2)
print("cube of a is ", a**3)
print( "cube of b is",b**3 )